package cc.hhhl.client.theme

data class ThemeCustomizationColorSwatch(val hex: String)

data class ThemeCustomizationTemplate(
    val label: String,
    val accentHex: String,
    val backgroundHex: String,
    val surfaceHex: String,
    val customTheme: HhhlCustomTheme,
)

object ThemeCustomizationCatalog {
    val placeholders = HhhlCustomTheme(
        accentColorHex = "#1D9BF0",
        accentSoftColorHex = "#E7F3FF",
        backgroundColorHex = "#000000",
        surfaceColorHex = "#080A0E",
        elevatedSurfaceColorHex = "#151C26",
        panelBackgroundColorHex = "#080A0E",
        chatBackgroundColorHex = "#000000",
        inputBackgroundColorHex = "#111720",
        cardBackgroundColorHex = "#080A0E",
        noteBackgroundColorHex = "#080A0E",
        primaryTextColorHex = "#E7E9EA",
        secondaryTextColorHex = "#94A1AF",
        mutedTextColorHex = "#7F8B99",
        dividerColorHex = "#232C36",
        borderColorHex = "#232C36",
        mediaBackgroundColorHex = "#0D1219",
        avatarBackgroundColorHex = "#0B2134",
        badgeBackgroundColorHex = "#0B2134",
        unreadBadgeColorHex = "#FF3B30",
        successColorHex = "#34C759",
        warningColorHex = "#FFB020",
        dangerColorHex = "#FF453A",
        dangerTextColorHex = "#FFFFFF",
        textInverseColorHex = "#FFFFFF",
        focusRingColorHex = "#1D9BF0",
        inputBorderColorHex = "#2F3336",
        inputFocusedBorderColorHex = "#1D9BF0",
        toastBackgroundColorHex = "#F5F5F7",
        toastTextColorHex = "#1D1D1F",
        rankBronzeColorHex = "#B87333",
        rankSilverColorHex = "#94A1AF",
        rankGoldColorHex = "#1D9BF0",
        rankPlatinumColorHex = "#FF453A",
        buttonBackgroundColorHex = "#0B2134",
        buttonSelectedBackgroundColorHex = "#123A59",
        chipBackgroundColorHex = "#0B2134",
        chipSelectedBackgroundColorHex = "#123A59",
        topBarBackgroundColorHex = "#080A0E",
        bottomNavBackgroundColorHex = "#080A0E",
        bottomNavSelectedColorHex = "#0B2134",
        incomingBubbleColorHex = "#121822",
        outgoingBubbleColorHex = "#3390EC",
        incomingBubbleTextColorHex = "#E6EEF5",
        outgoingBubbleTextColorHex = "#FFFFFF",
        chatBubbleBorderColorHex = "#25303A",
        chatComposerBackgroundColorHex = "#111720",
        chatMentionHighlightColorHex = "#0B2134",
        noteActionBackgroundColorHex = "#0B2134",
        noteReactionBackgroundColorHex = "#123A59",
        noteTreeLineColorHex = "#25303A",
        quoteBackgroundColorHex = "#111720",
        overlayScrimColorHex = "#000000",
        shadowColorHex = "#000000",
    )

    val templates = listOf(
        ThemeCustomizationTemplate(
            label = "X 清蓝",
            accentHex = "#1D9BF0",
            backgroundHex = "#F6F8FA",
            surfaceHex = "#FFFFFF",
            customTheme = lightTemplate(
                accent = "#1D9BF0",
                accentSoft = "#E7F3FF",
                background = "#F6F8FA",
                input = "#F1F4F7",
                line = "#E2E8EF",
                secondary = "#53606D",
                muted = "#66727F",
                media = "#EEF3F8",
                outgoing = "#1D9BF0",
            ),
        ),
        ThemeCustomizationTemplate(
            label = "TG 冰蓝",
            accentHex = "#2AABEE",
            backgroundHex = "#F1F7FC",
            surfaceHex = "#FFFFFF",
            customTheme = lightTemplate(
                accent = "#2AABEE",
                accentSoft = "#E1F3FD",
                background = "#F1F7FC",
                input = "#EAF4FA",
                line = "#D8EAF5",
                secondary = "#66839A",
                muted = "#66839A",
                media = "#EAF4FA",
                outgoing = "#2AABEE",
            ),
        ),
        ThemeCustomizationTemplate(
            label = "Apple 石墨",
            accentHex = "#007AFF",
            backgroundHex = "#F5F5F7",
            surfaceHex = "#FFFFFF",
            customTheme = lightTemplate(
                accent = "#007AFF",
                accentSoft = "#EAF4FF",
                background = "#F5F5F7",
                input = "#F2F2F7",
                line = "#E5E5EA",
                secondary = "#6E6E73",
                muted = "#6E6E73",
                media = "#F1F1F4",
                outgoing = "#007AFF",
            ),
        ),
        ThemeCustomizationTemplate(
            label = "OLED 蓝",
            accentHex = "#0A84FF",
            backgroundHex = "#000000",
            surfaceHex = "#050505",
            customTheme = darkTemplate(
                accent = "#0A84FF",
                accentSoft = "#0C1A28",
                background = "#000000",
                surface = "#050505",
                elevated = "#111113",
                input = "#111113",
                line = "#242426",
                secondary = "#98989D",
                muted = "#98989D",
                media = "#0E0E10",
                incoming = "#111113",
                outgoing = "#0A84FF",
            ),
        ),
        ThemeCustomizationTemplate(
            label = "TG 夜蓝",
            accentHex = "#58A6FF",
            backgroundHex = "#121A24",
            surfaceHex = "#182331",
            customTheme = darkTemplate(
                accent = "#58A6FF",
                accentSoft = "#16324B",
                background = "#121A24",
                surface = "#182331",
                elevated = "#223246",
                input = "#1D2A39",
                line = "#2B3B4B",
                secondary = "#94A8B8",
                muted = "#94A8B8",
                media = "#162130",
                incoming = "#172536",
                outgoing = "#2B6EA6",
            ),
        ),
        ThemeCustomizationTemplate(
            label = "紫粉夜",
            accentHex = "#F91880",
            backgroundHex = "#000000",
            surfaceHex = "#080A0E",
            customTheme = darkTemplate(
                accent = "#F91880",
                accentSoft = "#29111E",
                background = "#000000",
                surface = "#080A0E",
                elevated = "#151C26",
                input = "#141720",
                line = "#2B2630",
                secondary = "#94A1AF",
                muted = "#7F8B99",
                media = "#0F1118",
                incoming = "#121822",
                outgoing = "#F91880",
            ),
        ),
        ThemeCustomizationTemplate(
            label = "暖橙夜",
            accentHex = "#FF8A00",
            backgroundHex = "#000000",
            surfaceHex = "#080A0E",
            customTheme = darkTemplate(
                accent = "#FF8A00",
                accentSoft = "#2A1A0C",
                background = "#000000",
                surface = "#080A0E",
                elevated = "#151C26",
                input = "#141820",
                line = "#302B24",
                secondary = "#94A1AF",
                muted = "#7F8B99",
                media = "#0F1218",
                incoming = "#121822",
                outgoing = "#FF8A00",
            ),
        ),
    )

    val accentSwatches = themeSwatches(
        ThemePresetRegistry.presets.map { it.previewAccentHex },
    )

    val backgroundSwatches = themeSwatches(
        buildList {
            addAll(ThemePresetRegistry.presets.map { it.previewBackgroundHex })
            addAll(
                listOf(
                    "#F2F6F8",
                    "#EEF6FF",
                    "#F5F8F8",
                    "#11161D",
                    "#080A0E",
                    "#050506",
                    "#000000",
                ),
            )
        },
    )

    val chatBackgroundSwatches = themeSwatches(
        listOf(
            "#F7F9FA",
            "#F2F6F8",
            "#F5F5F7",
            "#EEF6FF",
            "#F5F8F8",
            "#F1F7FC",
            "#121A24",
            "#11161D",
            "#080A0E",
            "#000000",
        ),
    )

    val inputBackgroundSwatches = themeSwatches(
        listOf(
            "#FFFFFF",
            "#EFF3F4",
            "#F2F2F7",
            "#1D2A39",
            "#1C1C1E",
            "#111720",
            "#080A0E",
        ),
    )

    val cardBackgroundSwatches = themeSwatches(
        buildList {
            addAll(ThemePresetRegistry.presets.map { it.previewSurfaceHex })
            addAll(
                listOf(
                    "#F7F9FA",
                    "#F5F5F7",
                    "#171D26",
                    "#111114",
                    "#080A0E",
                ),
            )
        },
    )
}

private fun lightTemplate(
    accent: String,
    accentSoft: String,
    background: String,
    input: String,
    line: String,
    secondary: String,
    muted: String,
    media: String,
    outgoing: String,
): HhhlCustomTheme = HhhlCustomTheme(
    accentColorHex = accent,
    accentSoftColorHex = accentSoft,
    backgroundColorHex = background,
    surfaceColorHex = "#FFFFFF",
    elevatedSurfaceColorHex = "#FFFFFF",
    panelBackgroundColorHex = "#FFFFFF",
    chatBackgroundColorHex = background,
    inputBackgroundColorHex = input,
    cardBackgroundColorHex = "#FFFFFF",
    noteBackgroundColorHex = "#FFFFFF",
    primaryTextColorHex = "#0F1419",
    secondaryTextColorHex = secondary,
    mutedTextColorHex = muted,
    dividerColorHex = line,
    borderColorHex = line,
    mediaBackgroundColorHex = media,
    avatarBackgroundColorHex = accentSoft,
    badgeBackgroundColorHex = accentSoft,
    unreadBadgeColorHex = "#FF3B30",
    successColorHex = "#34C759",
    warningColorHex = "#FFB020",
    dangerColorHex = "#FF453A",
    dangerTextColorHex = "#FFFFFF",
    textInverseColorHex = "#FFFFFF",
    focusRingColorHex = accent,
    inputBorderColorHex = line,
    inputFocusedBorderColorHex = accent,
    toastBackgroundColorHex = "#0F1419",
    toastTextColorHex = "#FFFFFF",
    rankBronzeColorHex = "#B87333",
    rankSilverColorHex = secondary,
    rankGoldColorHex = accent,
    rankPlatinumColorHex = "#FF453A",
    buttonBackgroundColorHex = accentSoft,
    buttonSelectedBackgroundColorHex = accentSoft,
    chipBackgroundColorHex = input,
    chipSelectedBackgroundColorHex = accentSoft,
    topBarBackgroundColorHex = "#FFFFFF",
    bottomNavBackgroundColorHex = "#FFFFFF",
    bottomNavSelectedColorHex = accentSoft,
    incomingBubbleColorHex = "#FFFFFF",
    outgoingBubbleColorHex = outgoing,
    incomingBubbleTextColorHex = "#0F1419",
    outgoingBubbleTextColorHex = "#FFFFFF",
    chatBubbleBorderColorHex = line,
    chatComposerBackgroundColorHex = "#FFFFFF",
    chatMentionHighlightColorHex = accentSoft,
    noteActionBackgroundColorHex = accentSoft,
    noteReactionBackgroundColorHex = accentSoft,
    noteTreeLineColorHex = line,
    quoteBackgroundColorHex = input,
    overlayScrimColorHex = "#000000",
    shadowColorHex = "#000000",
)

private fun darkTemplate(
    accent: String,
    accentSoft: String,
    background: String,
    surface: String,
    elevated: String,
    input: String,
    line: String,
    secondary: String,
    muted: String,
    media: String,
    incoming: String,
    outgoing: String,
): HhhlCustomTheme = HhhlCustomTheme(
    accentColorHex = accent,
    accentSoftColorHex = accentSoft,
    backgroundColorHex = background,
    surfaceColorHex = surface,
    elevatedSurfaceColorHex = elevated,
    panelBackgroundColorHex = surface,
    chatBackgroundColorHex = background,
    inputBackgroundColorHex = input,
    cardBackgroundColorHex = surface,
    noteBackgroundColorHex = surface,
    primaryTextColorHex = "#E7E9EA",
    secondaryTextColorHex = secondary,
    mutedTextColorHex = muted,
    dividerColorHex = line,
    borderColorHex = line,
    mediaBackgroundColorHex = media,
    avatarBackgroundColorHex = accentSoft,
    badgeBackgroundColorHex = accentSoft,
    unreadBadgeColorHex = "#FF3B30",
    successColorHex = "#34C759",
    warningColorHex = "#FFB020",
    dangerColorHex = "#FF453A",
    dangerTextColorHex = "#FFFFFF",
    textInverseColorHex = "#FFFFFF",
    focusRingColorHex = accent,
    inputBorderColorHex = line,
    inputFocusedBorderColorHex = accent,
    toastBackgroundColorHex = "#F5F5F7",
    toastTextColorHex = "#1D1D1F",
    rankBronzeColorHex = "#B87333",
    rankSilverColorHex = secondary,
    rankGoldColorHex = accent,
    rankPlatinumColorHex = "#FF453A",
    buttonBackgroundColorHex = accentSoft,
    buttonSelectedBackgroundColorHex = accentSoft,
    chipBackgroundColorHex = input,
    chipSelectedBackgroundColorHex = accentSoft,
    topBarBackgroundColorHex = surface,
    bottomNavBackgroundColorHex = surface,
    bottomNavSelectedColorHex = accentSoft,
    incomingBubbleColorHex = incoming,
    outgoingBubbleColorHex = outgoing,
    incomingBubbleTextColorHex = "#E7E9EA",
    outgoingBubbleTextColorHex = "#FFFFFF",
    chatBubbleBorderColorHex = line,
    chatComposerBackgroundColorHex = input,
    chatMentionHighlightColorHex = accentSoft,
    noteActionBackgroundColorHex = accentSoft,
    noteReactionBackgroundColorHex = accentSoft,
    noteTreeLineColorHex = line,
    quoteBackgroundColorHex = input,
    overlayScrimColorHex = "#000000",
    shadowColorHex = "#000000",
)

private fun themeSwatches(hexes: Iterable<String>): List<ThemeCustomizationColorSwatch> {
    return hexes
        .map { hex -> hex.trim() }
        .filter { hex -> hex.isNotEmpty() }
        .map { hex ->
            val clean = hex.removePrefix("#").uppercase()
            "#$clean"
        }
        .distinct()
        .map(::ThemeCustomizationColorSwatch)
}
